config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#Old Routes from mod2 project

  # resources :books, :only => [:index, :show, :create, :new, :destroy] do
  #   resources :reviews, :only => [:new, :create]
  # end
  # resources :reviews, :only => [:destroy]
  # resources :authors, :except => [:index, :edit, :update ]
  # resources :users, :only => [:show, :new, :create]

#Refactored Routes for mod3 prework

  get '/books/new', to: "books#new", as: 'new_book'
  get '/books', to: "books#index", as: 'books'
  get '/books/:id', to: "books#show"
  post '/books', to: "books#create"
  delete '/books/:id', to: "books#destroy", as: 'book'

  get '/books/:book_id/reviews/new', to: "reviews#new", as: 'new_book_review'
  post '/books/:book_id/reviews', to: "reviews#create", as: 'book_reviews'

  delete '/reviews/:id', to: "reviews#destroy", as: 'review'

  get '/authors/new', to: "authors#new", as: 'new_author'
  post '/authors', to: "authors#create"
  get '/authors/:id', to: "authors#show", as: 'author'
  delete '/authors/:id', to: "authors#destroy"

  get '/users/:id', to: "users#show", as: 'user'
  get '/users/new', to: "users#new", as: 'new_user'
  post '/users', to: "users#create" 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates_presence_of :name

  has_many :book_authors
  has_many :books, through: :book_authors, dependent: :destroy

  def self.authors_by_book(hash)
    array = hash[:authors].split(', ')
    new_array = array.map do |author|
      author.strip!
      self.find_or_create_by(name: author.titlecase)
    end
    hash[:authors] = new_array
  end
end

app/models/book.rb
class Book < ApplicationRecord
  validates_presence_of :title, :pages, :year

  has_many :book_authors
  has_many :reviews
  has_many :authors, through: :book_authors, dependent: :destroy
  has_many :users, through: :reviews, dependent: :destroy

  def review_count
    reviews.size
  end

  def other_authors(id)
    authors.where.not(id: id)
  end

  def avg_rating
    reviews.average(:score).to_f.round(1)
  end

  def top_review
    sort_reviews('DESC').first
  end

  def top_3_reviews
    sort_reviews('DESC').first(3)
  end

  def bottom_3_reviews
    sort_reviews('ASC').first(3)
  end

  def sort_reviews(dir)
    reviews.order("score #{dir}")
  end

  def self.show_3_by_rating(dir)
    Book.do_sort('avg_rating', dir).first(3)
  end

  def self.do_sort(trait, dir)
    Book.select('books.*, avg(score) as avg_rating, count(reviews) as review_count').joins(:reviews).group(:book_id, :id).order("#{trait} #{dir}")
  end

end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  validates_presence_of :title, :description, :score

  validates :score, numericality: {
    only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }

  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name

  has_many :reviews
  has_many :books, through: :reviews

  def self.top_3
    User.do_sort('DESC').first(3)
  end

  def self.do_sort(dir)
    User.select('users.*, count(reviews) as review_count').joins(:reviews).group(:user_id, :id).order("review_count #{dir}")
  end

  def sort_reviews(trait, dir)
    reviews.order("#{trait} #{dir}")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def show
    @author = Author.find(params[:id])
  end

  def destroy
    @author = Author.find(params[:id])
    books = @author.books
    books.each do |book|
      book.destroy if book.authors.count < 2
    end
    @author.destroy
    redirect_to books_path
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    if params[:sorting]
      @books = Book.do_sort(params[:sorting], params[:direction])
    else
      @books = Book.all
    end
    @best_rated_books = Book.show_3_by_rating('DESC')
    @worst_rated_books = Book.show_3_by_rating('ASC')
    @top_reviewers = User.top_3
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new()
  end

  def create
    params_hash = book_params
    params_hash[:title] = params_hash[:title].titlecase
    data =  Author.authors_by_book(params_hash)
    @book = Book.create(params_hash)
    redirect_to books_path
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

# This block should be last in the controller
  private

  def book_params
    params.require(:book).permit(:title, :pages, :year, :authors)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @book = Book.find(params[:book_id])
    @review = Review.new()
  end

  def create
    @user = User.find_or_create_by(name: review_params[:user])
    @book = Book.find(params[:book_id])
    hash = review_params
    hash[:user] = @user
    @review = @book.reviews.create(hash)
    redirect_to book_path(@book)
  end

  def destroy
    review = Review.find(params[:id])
    @user = review.user
    review.destroy
    redirect_to user_path(@user)
  end

  private

  def review_params
    params.require(:review).permit(:user, :title, :description, :score, :book_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    if params[:sorting]
      @reviews = @user.sort_reviews(params[:sorting], params[:direction])
    else @reviews = @user.reviews
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/show.html.erb
<div class="author_show_header">
  <h1><%=@author.name%></h1>
  <div class="delete">
    <%= link_to "Delete Author", author_path(@author), method: "delete"  %>
  </div>
</div>

<div class="author_book_list">
  <h2>Books:</h2>
    <%@author.books.each do |book|%>
    <div class="author_book_card">
      <h4><u><span class="book_link"><%= link_to "#{book.title}", book_path(book) %></span></u><h4>
      <ul>
        <li>Pages: <%=book.pages%></li>
        <% if book.other_authors(@author.id).size > 0 %>
          <li>Written with:
            <ul>
              <%book.other_authors(@author.id).each do |auth|%>
                <li><%= link_to "#{auth.name}", author_path(auth) %></li>
              <% end %></ul>
          </li>
        <% end %>
        <li>Top Review: <%= book.top_review.title %></li>
        <ul>
          <li>Score: <%=book.top_review.score%></li>
          <li>Reviewed By: <span class="user_link"><%= link_to "#{book.top_review.user.name}", user_path(book.top_review.user) %></span></li>
        </ul>
      </ul>
    </div>
    <% end %>
  </div>

app/views/books/index.html.erb
<h1>Books</h1>

<div class="stats_box">

  <u>Best-Rated Books:</u>
    <% @best_rated_books.each do |book| %>
    <div>
      <ul class="best_books">
        <li><span class="book_link"><%= link_to "#{book.title}", book_path(book) %></span></li>
      </ul>
      <% end %>
    </div>

  <u>Worst-Rated Books:</u>
    <% @worst_rated_books.each do |book| %>
    <div>
      <ul class="worst_books">
        <li> <span class="book_link"><%= link_to "#{book.title}", book_path(book) %></span> </li>
      </ul>
    </div>
    <% end %>

  <u>Top Reviewers:</u>
    <% @top_reviewers.each do |user| %>
    <div>
      <ul class="top_reviewers">
        <li><span class="user_link"><%= link_to "#{user.name}", user_path(user) %></span></li>
      </ul>
    </div>
  <% end %>
</div>

<p id="sort_links">Sort By:
  <a id="best-rated" href="/books?sorting=avg_rating&direction=DESC">Best-Rated</a> /
  <a id="worst-rated" href="/books?sorting=avg_rating&direction=ASC">Worst-Rated</a> /
  <a id="most-pages" href="/books?sorting=pages&direction=DESC">Most-Pages</a> /
  <a id="fewest-pages" href="/books?sorting=pages&direction=ASC">Fewest-Pages</a> /
  <a id="most-reviewed" href="/books?sorting=review_count&direction=DESC">Most-Reviewed</a> /
  <a id="least-reviewed" href="/books?sorting=review_count&direction=ASC">Least-Reviewed</a>
</p>

<div class="new_content">
    <a id="new_book" href="/books/new">Click Here To Add A New Book</a>
</div>

<div class="book_section">
  <% @books.each do |book| %>
    <div class="book_card" id="book-<%= book.id %>">
    <h2><u><span class="book_link"><%= link_to "#{book.title}", book_path(book) %></span></u></h2>
    <ul class="book_stats">
      <li>Author(s):
        <% book.authors.each do |auth| %>
        <ul class="book_authors">
          <li> <%= link_to "#{auth.name}", author_path(auth) %> </li>
        </ul></li>
      <% end %>
      <li>Pages: <%= book.pages %></li>
      <li>Year: <%= book.year %> </li>
      <li>Average Rating: <%= book.avg_rating %>
        <ul class="ratings_count">
          <li>Based on <%= book.review_count %> review(s)</li>
        </ul></li>
    </ul>
  </div>
  <% end %>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>
<div class="form_new">
  <div class="container_1">

    <%= form_for @book do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title%> <br />

      <%= f.label :pages %>
      <%= f.text_field :pages%> <br />

      <%= f.label :year %>
      <%= f.text_field :year%> <br />

      <%= f.label :authors %>
      <p>Input Authors first name last name (separate multiple authors with , )</p>
      <input type="text" name="book[authors]" placeholder="Author Names"> <br />

      <%= f.submit %>
    <%end%>
  </div>
</div>

app/views/books/show.html.erb
<div class="book_show_header">
  <h1><u><%=@book.title%></u></h1>
  <div class="delete">
    <%=link_to "Delete Book", book_path(@book), method: "delete"%>
  </div>
  <div class="book_show_info">
    <% @book.authors.each do |auth| %>
      <p>By: <%= link_to "#{auth.name}", author_path(auth) %></p>
    <% end %>
    <p>Pages: <%=@book.pages%> </p>
  </div>
</div>


<div class="book_show_stats">
  <p>Average Rating: <%=@book.avg_rating%></p>
  <div class="top_3_reviews"
    <p>Top 3 reviews:</p>
    <ul>
      <% @book.top_3_reviews.each do |rev| %>
      <li><u><%=rev.title%></u>, by <span class="user_link"><%= link_to "#{rev.user.name}", user_path(rev.user)%></span>, Rating: <%=rev.score%></li>
      <% end %>
    </ul>
  </div>
  <div class="bottom_3_reviews">
    <p>Bottom 3 reviews:</p>
    <ul>
      <% @book.bottom_3_reviews.each do |rev| %>
      <li><u><%=rev.title%></u>, by <span class="user_link"><%= link_to "#{rev.user.name}", user_path(rev.user)%></span>, Rating: <%=rev.score%></li>
      <% end %>
    </ul>
  </div>
</div>


<h4>Reviews:</h4>
<span class="new_review">
  <%= link_to "Click Here To Add A New Review", new_book_review_path(@book)  %>
</span>
<div class="reviews_block">
  <% @book.reviews.each do |rev| %>
  <div class="review">
    <p><u><%=rev.title%></u>, by <span class="user_link"><%= link_to "#{rev.user.name}", user_path(rev.user)%></span></p>
    <p>Score: <%=rev.score%></p>
    <p>Review: "<%=rev.description%>"</p>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClub</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Mali" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<div class="form_new">
  <div class="container_2">

    <%= form_for [@book, @review] do |f| %>
      <%= f.label :user %>
      <%= f.text_field :user, placeholder: "User Name" %> <br />

      <%= f.label :title %>
      <%= f.text_field :title%> <br />

      <%= f.label :description %>
      <%= f.text_area :description%> <br />

      <%= f.label :score %>
      <%= f.text_field :score%> <br />

      <%= f.submit %>
    <%end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user_show_header">
  <h1> <%= @user.name %> </h1>
</div>

<div class="sort_reviews_links">
<p>Sort Reviews:
  <a href="/users/<%= @user.id%>?sorting=created_at&direction=DESC" >Newest-First</a> /
  <a href= "/users/<%=@user.id%>?sorting=created_at&direction=ASC" >Oldest-First</a>
</p>
</div>

<div class="user_show_reviews">
    <% @reviews.each do |rev| %>
      <div class="review">
        <span class="review_<%= rev.id  %>">
          <%= rev.title %>
        </span>
        <ul>
          <li> <%= rev.score %> </li>
          <li> <%= rev.description %> </li>
        </ul>
        <div class="delete" id="delete_<%= rev.id %>"><%= link_to "Delete Review", review_path(rev), method: "delete" %></div >
      </div>
    <% end %>
</div>